### ISSUE TITLE
matlib parse fails on MacOS10.7 but works on Ubuntu 10.04 (migrated from Trac #2003)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#3732]
Original ticket http://projects.scipy.org/numpy/ticket/2003
Reported 2011-12-22 by trac user hajons, assigned to unknown.

I have attached a script that parses a matlab file and stores data in a file. It works well on Ubuntu 10.04 with python 2.6.5, but fails on MacOs 10.7 both on python 2.6.1 and 2.7.1 (MacOS version of python). I don't have any other problems with python on MacOS. Scipy version 0.11 and numpy version 2.0.0.

The error message I get on MacOS is this:
seldmac6145:Proximates 23056164$ python parse_proximity.py realitymining.mat 
Done loading matlab data.
Traceback (most recent call last):
  File "parse_proximity.py", line 79, in <module>
    get_events(matlab_obj)
  File "parse_proximity.py", line 18, in get_events
    subject_mac = int(subject_object.my_mac[0][0][0], 16)
AttributeError: 'numpy.void' object has no attribute 'my_mac'

**Comment by thouis** [comment]
Attachment in Trac by trac user hajons, 2011-12-22: [parse_network.py](http://projects.scipy.org/numpy/attachment/ticket/2003/parse_network.py)

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2011-12-30

I suspect this is unrelated to numpy or scipy.  `subject_object` in your error message is a numpy.void object, which certainly doesn't have a `my_mac` attribute. 

So I recommend you investigate yourself. If you manage to isolate the bug and it is numpy related after all, please provide an example that is as small as possible and allows to reproduce the issue.
