### ISSUE TITLE
Numpy doesn't build with llvm-gcc on OS X 10.7 (Lion) (migrated from Trac #1951)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#3499]
Original ticket http://projects.scipy.org/numpy/ticket/1951
Reported 2011-09-10 by atmention:fonnesbeck, assigned to unknown.

The current main repository code no longer builds on OSX 10.7. Sometime during the last 3 weeks, something in multiarray was broken. Here is the relevant part of the build log:

```
In file included from numpy/core/src/multiarray/multiarraymodule_onefile.c:45:
numpy/core/src/multiarray/lowlevel_strided_loops.c.src: At top level:
numpy/core/src/multiarray/lowlevel_strided_loops.c.src:314: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘*’ token
numpy/core/src/multiarray/lowlevel_strided_loops.c.src:469: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘*’ token
numpy/core/src/multiarray/lowlevel_strided_loops.c.src:469: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘*’ token
numpy/core/src/multiarray/lowlevel_strided_loops.c.src:851: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘*’ token
numpy/core/src/multiarray/lowlevel_strided_loops.c.src:932: error: expected declaration specifiers or ‘...’ before ‘PyArray_StridedTransferFn’
numpy/core/src/multiarray/lowlevel_strided_loops.c.src:934: error: conflicting types for ‘PyArray_TransferNDimToStrided’
numpy/core/src/private/lowlevel_strided_loops.h:317: error: previous declaration of ‘PyArray_TransferNDimToStrided’ was here
numpy/core/src/multiarray/lowlevel_strided_loops.c.src: In function ‘PyArray_TransferNDimToStrided’:
numpy/core/src/multiarray/lowlevel_strided_loops.c.src:943: warning: implicit declaration of function ‘stransfer’
numpy/core/src/multiarray/lowlevel_strided_loops.c.src: At top level:
numpy/core/src/multiarray/lowlevel_strided_loops.c.src:1051: error: expected declaration specifiers or ‘...’ before ‘PyArray_StridedTransferFn’
numpy/core/src/multiarray/lowlevel_strided_loops.c.src:1053: error: conflicting types for ‘PyArray_TransferStridedToNDim’
numpy/core/src/private/lowlevel_strided_loops.h:327: error: previous declaration of ‘PyArray_TransferStridedToNDim’ was here
numpy/core/src/multiarray/lowlevel_strided_loops.c.src:1171: error: expected declaration specifiers or ‘...’ before ‘PyArray_MaskedStridedTransferFn’
numpy/core/src/multiarray/lowlevel_strided_loops.c.src:1173: error: conflicting types for ‘PyArray_TransferMaskedStridedToNDim’
numpy/core/src/private/lowlevel_strided_loops.h:338: error: previous declaration of ‘PyArray_TransferMaskedStridedToNDim’ was here
In file included from numpy/core/src/multiarray/multiarraymodule_onefile.c:47:
numpy/core/src/multiarray/einsum.c.src: In function ‘PyArray_EinsteinSum’:
numpy/core/src/multiarray/einsum.c.src:3016: warning: implicit declaration of function ‘PyArray_FillWithZero’
In file included from numpy/core/src/multiarray/multiarraymodule_onefile.c:49:
numpy/core/src/multiarray/array_assign_scalar.c: At top level:
numpy/core/src/multiarray/array_assign_scalar.c:335: error: conflicting types for ‘PyArray_AssignRawScalar’
numpy/core/src/multiarray/array_assign_scalar.c:335: note: an argument type that has a default promotion can’t match an empty parameter name list declaration
numpy/core/src/multiarray/convert.c:407: error: previous implicit declaration of ‘PyArray_AssignRawScalar’ was here
In file included from numpy/core/src/multiarray/multiarraymodule_onefile.c:50:
numpy/core/src/multiarray/array_assign_array.c:392: error: conflicting types for ‘PyArray_AssignArray’
numpy/core/src/multiarray/array_assign_array.c:392: note: an argument type that has a default promotion can’t match an empty parameter name list declaration
numpy/core/src/multiarray/ctors.c:2907: error: previous implicit declaration of ‘PyArray_AssignArray’ was here
numpy/core/src/multiarray/array_assign_array.c: In function ‘PyArray_AssignArray’:
numpy/core/src/multiarray/array_assign_array.c:403: warning: initialization makes pointer from integer without a cast
numpy/core/src/multiarray/array_assign_array.c:407: warning: implicit declaration of function ‘PyArray_AssignNA’
In file included from numpy/core/src/multiarray/multiarraymodule_onefile.c:51:
numpy/core/src/multiarray/reduction.c: At top level:
numpy/core/src/multiarray/reduction.c:801: error: conflicting types for ‘PyArray_ReduceWrapper’
numpy/core/src/multiarray/item_selection.c:2028: error: previous implicit declaration of ‘PyArray_ReduceWrapper’ was here
In file included from numpy/core/src/multiarray/multiarraymodule_onefile.c:52:
numpy/core/src/multiarray/na_mask.c:55: error: static declaration of ‘PyArray_ContainsNA’ follows non-static declaration
numpy/core/src/multiarray/common.c:104: error: previous implicit declaration of ‘PyArray_ContainsNA’ was here
numpy/core/src/multiarray/na_mask.c:243: error: conflicting types for ‘PyArray_AssignMaskNA’
numpy/core/src/multiarray/na_mask.c:243: note: an argument type that has a default promotion can’t match an empty parameter name list declaration
numpy/core/src/multiarray/ctors.c:2670: error: previous implicit declaration of ‘PyArray_AssignMaskNA’ was here
numpy/core/src/multiarray/na_mask.c:331: error: conflicting types for ‘PyArray_AllocateMaskNA’
numpy/core/src/multiarray/na_mask.c:331: note: an argument type that has a default promotion can’t match an empty parameter name list declaration
numpy/core/src/multiarray/flagsobject.c:286: error: previous implicit declaration of ‘PyArray_AllocateMaskNA’ was here
numpy/core/src/multiarray/na_mask.c:468: error: conflicting types for ‘PyArray_AssignNA’
numpy/core/src/multiarray/na_mask.c:468: note: an argument type that has a default promotion can’t match an empty parameter name list declaration
numpy/core/src/multiarray/array_assign_array.c:407: error: previous implicit declaration of ‘PyArray_AssignNA’ was here
numpy/core/src/multiarray/na_mask.c: In function ‘PyArray_IsNA’:
numpy/core/src/multiarray/na_mask.c:500: error: ‘NpyNA_Type’ undeclared (first use in this function)
In file included from numpy/core/src/multiarray/multiarraymodule_onefile.c:53:
numpy/core/src/multiarray/na_object.c: In function ‘na_call’:
numpy/core/src/multiarray/na_object.c:84: error: ‘NpyNA_Type’ undeclared (first use in this function)
numpy/core/src/multiarray/na_object.c: In function ‘na_richcompare’:
numpy/core/src/multiarray/na_object.c:164: warning: assignment makes pointer from integer without a cast
numpy/core/src/multiarray/na_object.c: In function ‘NpyNA_CombineNA’:
numpy/core/src/multiarray/na_object.c:285: error: ‘NpyNA_Type’ undeclared (first use in this function)
numpy/core/src/multiarray/na_object.c: In function ‘NpyNA_CombineNAWithObject’:
numpy/core/src/multiarray/na_object.c:328: error: ‘NpyNA_Type’ undeclared (first use in this function)
numpy/core/src/multiarray/na_object.c: At top level:
numpy/core/src/multiarray/na_object.c:424: error: conflicting types for ‘NpyNA_FromObject’
numpy/core/src/multiarray/scalarapi.c:824: error: previous implicit declaration of ‘NpyNA_FromObject’ was here
numpy/core/src/multiarray/na_object.c: In function ‘NpyNA_FromObject’:
numpy/core/src/multiarray/na_object.c:426: error: ‘NpyNA_Type’ undeclared (first use in this function)
numpy/core/src/multiarray/na_object.c: At top level:
numpy/core/src/multiarray/na_object.c:489: error: conflicting types for ‘NpyNA_FromDTypeAndPayload’
numpy/core/src/multiarray/mapping.c:1806: error: previous implicit declaration of ‘NpyNA_FromDTypeAndPayload’ was here
numpy/core/src/multiarray/na_object.c: In function ‘NpyNA_FromDTypeAndPayload’:
numpy/core/src/multiarray/na_object.c:493: error: ‘Npy_NA’ undeclared (first use in this function)
numpy/core/src/multiarray/na_object.c:497: error: ‘NpyNA_Type’ undeclared (first use in this function)
numpy/core/src/multiarray/na_object.c: In function ‘na_binaryop’:
numpy/core/src/multiarray/na_object.c:551: error: ‘NpyNA_Type’ undeclared (first use in this function)
numpy/core/src/multiarray/na_object.c: In function ‘na_and’:
numpy/core/src/multiarray/na_object.c:577: error: ‘NpyNA_Type’ undeclared (first use in this function)
numpy/core/src/multiarray/na_object.c: In function ‘na_or’:
numpy/core/src/multiarray/na_object.c:615: error: ‘NpyNA_Type’ undeclared (first use in this function)
error: Command "llvm-gcc-4.2 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -arch x86_64 -pipe -Inumpy/core/include -Ibuild/src.macosx-10.7-x86_64-2.7/numpy/core/include/numpy -Inumpy/core/src/private -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -Inumpy/core/include -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -Ibuild/src.macosx-10.7-x86_64-2.7/numpy/core/src/multiarray -Ibuild/src.macosx-10.7-x86_64-2.7/numpy/core/src/umath -c numpy/core/src/multiarray/multiarraymodule_onefile.c -o build/temp.macosx-10.7-x86_64-2.7/numpy/core/src/multiarray/multiarraymodule_onefile.o" failed with exit status 1
```

**Comment by thouis** [comment]
Comment in Trac by atmention:mwiebe, 2011-09-11

**Comment by thouis** [comment]
Comment in Trac by atmention:charris, 2011-09-11

Builds with no problem on OSX 10.8 with Python 2.7. Have you cleaned out the build directory, made sure you are in the right branch, and done all the other stuff to make sure nothing extraneous is gumming things up?

**Comment by thouis** [comment]
Comment in Trac by atmention:fonnesbeck, 2011-09-11

Yes, I am sure. I compile new builds of numpy every couple of weeks using the exact same script, which trashes the build directory entirely every time. I am just pulling from the Github repo as usual.

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2012-03-26

Haven't seen this before, not sure if it's still relevant. If so: the date this ticket was opened is around the release date of OS X 10.7. So did it ever build with llvm-gcc? I'd guess not, based on the problems everyone else has with it. 

Clang on 10.7 does work by the way.

**Comment by thouis** [comment]
Comment in Trac by atmention:fonnesbeck, 2012-03-27

Never did get it working with LLVM-gcc. Works fine with clang, yes.

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2012-03-27

OK, thanks. I don't think there's an open numpy ticket for the llvm-gcc issue, so this is it. I'll change the title to match the issue. The corresponding scipy ticket is http://projects.scipy.org/scipy/ticket/1500.

**Comment by thouis** [comment]
Comment in Trac by atmention:rkern, 2012-03-28

numpy builds fine for me on 10.7 using llvm-gcc-4.2 from Xcode 4.1.

**Comment by thouis** [comment]
Comment in Trac by atmention:fonnesbeck, 2012-03-28

Right, so I eventually got this to build using llvm-gcc shortly after I reported this, but when I upgraded to Xcode 4.3.2 it broke again.
