### ISSUE TITLE
NumPy trunk doesn't compile on Windows (migrated from Trac #898)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#1505]
Original ticket http://projects.scipy.org/numpy/ticket/898
Reported 2008-08-29 by atmention:alberts, assigned to atmention:cournape.

!NumPy trunk r5726 fails to compile on Windows Vista Business 64-bit with Python 2.6b2 and Visual Studio 2008.

```
umathmodule.c
numpy\core\src\umathmodule.c.src(64) : error C2059: syntax error : 'type'
numpy\core\src\umathmodule.c.src(70) : error C2059: syntax error : 'type'
numpy\core\src\ufuncobject.c(1701) : warning C4244: '=' : conversion from 'npy_intp' to 'int', possible loss of data
numpy\core\src\ufuncobject.c(2422) : warning C4244: '=' : conversion from 'npy_intp' to 'int', possible loss of data
```

Build log attached.

**Comment by thouis** [comment]
Attachment in Trac by atmention:alberts, 2008-08-29: [build.txt](http://projects.scipy.org/numpy/attachment/ticket/898/build.txt)

**Comment by thouis** [comment]
Comment in Trac by atmention:cournape, 2008-08-31

1.2 will not support 2.6, since 2.6 won't be released before numpy 1.2 (hopefully).

**Comment by thouis** [comment]
Comment in Trac by atmention:alberts, 2008-08-31

That's extremely disappointing. Now is the time to test !NumPy with Python 2.6 so that we can make sure Python 2.6 isn't released with bugs that affect !NumPy.

**Comment by thouis** [comment]
Comment in Trac by atmention:cournape, 2008-08-31

Testing is one thing, but we are really close to release 1.2, and I think it is too late to thoroughly support 2.6, specially on Vista 64 bits with Vs 2008 (new platform, new python, new compiler, nose does not work with 2.6 correctly, I believe, which means we cannot test easily).

**Comment by thouis** [comment]
Comment in Trac by atmention:cournape, 2008-08-31

FWIW, it is a windows/visual studio issue, not a python 2.6 issue.

It builds ok on linux, but with a fair bunch of warnings and cannot be tested because nose is not 2.6 complient (or 2.6 has bugs: http://code.google.com/p/python-nose/issues/detail?id=161)

**Comment by thouis** [comment]
Comment in Trac by atmention:alberts, 2008-09-09

Ok, I've done some more digging.

If I make the following changes to the generated umathmodule.c it compiles with Python 2.6 and Visual Studio 2008 on Vista x64:

```
--- umathmodule.c.orig  2008-09-10 00:13:09.000000000 +0200
+++ umathmodule.c       2008-09-10 00:30:10.000000000 +0200
atmention:atmention: -73,12 +73,14 atmention:atmention:
 #endif

 #ifndef HAVE_FREXPF
+#undef frexpf
 static float frexpf(float x, int * i)
 {
     return (float)frexp((double)(x), i);
 }
 #endif
 #ifndef HAVE_LDEXPF
+#undef ldexpf
 static float ldexpf(float x, int i)
 {
     return (float)ldexp((double)(x), i);
```

So I suspect HAVE_FREXPF and HAVE_LDEXPF are not being defined when in fact they should be.

Can't do the build with numscons yet, because of this bug: https://bugs.launchpad.net/numpy.scons.support/+bug/268343

**Comment by thouis** [comment]
Comment in Trac by atmention:cournape, 2008-09-10

For numscons, it is more or less a scons issue. I am working on it, though, but it takes time to be in a good shape for upstream integration (scons 1.1, hopefully, I have several hours this week to work on this).

For the normal build process: did you managed to build the whole numpy ? Because at this stage, I expect to see problems with long strings literals handling (in mtrand.c). I did not test visual studio x64, though. 

For the umath problem, that's something that will be simplified and fixed in my branch clean_math_config; the whole thing is just too messy now, and instead of band-aid after band-aid, I think it just needs some surgery.

But nose being usable on 2.6 with a simple hack means it is much more likely to see those issues fixed (at least by me).

**Comment by thouis** [comment]
Comment in Trac by atmention:alberts, 2008-09-10

I haven't built past umathmodule.c. But I'll do it now and see how far I get.

Not sure what's going on with nose. I think there's still a bug in Python trunk, but I need the help of the nose folks to report it to the Python folks, and the nose folks aren't responding to my bug report.

**Comment by thouis** [comment]
Comment in Trac by atmention:alberts, 2008-09-10

With the two #undefs added to umathmodule.c.src, the build completes succesfully with VS2008 and Python 2.6b2 64-bit.

Now we just need to get nose/Python fixed...

**Comment by thouis** [comment]
Comment in Trac by atmention:alberts, 2008-09-10

Another strange bit of info: looks like nose 0.10.3 works with Python 2.6b2, but not with newer versions. So I'm guessing Python is at fault here.

**Comment by thouis** [comment]
Comment in Trac by atmention:alberts, 2008-09-10

Test failures with Python 2.6b2 and !NumPy 1.3.0.dev5800:

```
======================================================================
FAIL: Check formatting.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python26\Lib\site-packages\numpy\core\tests\test_print.py", line 28, in test_complex_types
    assert_equal(str(t(x)), str(complex(x)))
  File "C:\Python26\Lib\site-packages\numpy\testing\utils.py", line 183, in assert_equal
    raise AssertionError(msg)
AssertionError:
Items are not equal:
 ACTUAL: '(1e+020+0j)'
 DESIRED: '(1e+20+0j)'

======================================================================
FAIL: Check formatting.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python26\Lib\site-packages\numpy\core\tests\test_print.py", line 16, in test_float_types
    assert_equal(str(t(x)), str(float(x)))
  File "C:\Python26\Lib\site-packages\numpy\testing\utils.py", line 183, in assert_equal
    raise AssertionError(msg)
AssertionError:
Items are not equal:
 ACTUAL: '1e+020'
 DESIRED: '1e+20'

======================================================================
FAIL: test_umath.TestComplexFunctions.test_against_cmath
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python26\Lib\site-packages\nose\case.py", line 182, in runTest
    self.test(*self.arg)
  File "C:\Python26\Lib\site-packages\numpy\core\tests\test_umath.py", line 266, in test_against_cmath
    assert abs(a - b) < atol, "%s %s: %s; cmath: %s"%(fname,p,a,b)
AssertionError: arcsin 2: (1.57079632679-1.31695789692j); cmath: (1.57079632679+1.31695789692j)

======================================================================
FAIL: Test _check_fill_value
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python26\Lib\site-packages\numpy\ma\tests\test_core.py", line 914, in test_check_on_scalar
    assert_equal(fval, default_fill_value(0))
  File "C:\Python26\Lib\site-packages\numpy\ma\testutils.py", line 97, in assert_equal
    assert desired == actual, msg
AssertionError:
Items are not equal:
 ACTUAL: 72548393
 DESIRED: 999999

----------------------------------------------------------------------
Ran 1577 tests in 5.781s

FAILED (KNOWNFAIL=1, failures=4)
<nose.result.TextTestResult run=1577 errors=0 failures=4>
```

**Comment by thouis** [comment]
Comment in Trac by atmention:charris, 2008-11-13

Numpy now compiles on the window buildbot. Can you give it a shot and see if it works on your machine?

**Comment by thouis** [comment]
Comment in Trac by atmention:cournape, 2008-12-23

The formatting errors are still there, although relatively harmless (the formatting is different but not 'wrong' per se).

Everything else should be fixed: I could build numpy with the MS compiler included with the PSDK 6.1 for x86_64.

**Comment by thouis** [comment]
Comment in Trac by atmention:mwiebe, 2011-05-31
