### ISSUE TITLE
asbytes function missed (migrated from Trac #2115)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#3661]
Original ticket http://projects.scipy.org/numpy/ticket/2115
Reported 2012-04-24 by trac user mcilfone, assigned to atmention:rgommers.

Working with Scipy 0.9.0, stats module of Scipy, Numpy 1.4.1 and Python2.5, I get an import error on the following line

from scipy import stats

The error is

'<type 'exceptions.ImportError'>: cannot import name asbytes
      args = ('cannot import name asbytes',)
      message = 'cannot import name asbytes'

in file
 C:\Python25\lib\site-packages\scipy\optimize\linesearch.py in ()
    2 import numpy as np
    3 from numpy.compat import asbytes
    4
    5 **all** = ['line_search_wolfe1', 'line_search_wolfe2',
    6 'scalar_search_wolfe1', 'scalar_search_wolfe2',
numpy undefined, asbytes undefined

In the source code of NumPy 1.4.1, I don't find this function.

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2012-04-24

Hi, scipy 0.9.0 requires numpy 1.5.0 or higher.
