### ISSUE TITLE
regression for SWIG based code in 1.6.0 (migrated from Trac #1851)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#3399]
Original ticket http://projects.scipy.org/numpy/ticket/1851
Reported 2011-05-29 by atmention:rgommers, assigned to atmention:pearu.

Reported on the mailing list:
    line 332, in build_extension_sources
         sources = self.swig_sources(sources, ext)
       File
    "/home/bsesar/usr/pydebug/lib/python2.7/site-packages/numpy/distutils/command/build_src.py",

```
line 646, in swig_sources
     extension.swig_opts.remove('-c++')
AttributeError: 'str' object has no attribute 'remove'
```

The reason is that {{{swig_opts}}} is a string. This bug was introduced in commit:ff0822c4 and can be fixed by inserting
        if isinstance(extension.swig_opts, basestring):
            extension.swig_opts = extension.swig_opts.split()
just above the if-block where the error occurs.

Pearu, since you made that change, can you please check this fix is correct and complete?

**Comment by thouis** [comment]
Comment in Trac by atmention:pearu, 2011-05-30

This is not a bug in numpy.distutils but a of misuse of the swig_opts by the user.

According to documentation of std distutils Extension class:
          swig_opts : [string]
            any extra options to pass to SWIG if a source file has the .i
            extension.
swig_opts should be a list of strings.

If we are going to support string swig_opts as suggested, then this
will contradict with distutils docs. Note that the distutils/command/build_ext.py
assumes that extension.swig_opts is a list.

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2011-05-30

Well, it will not break anything. I still think we should check for a string, and then either convert to list, raise a warning or raise an informative error. Right now it's hard to make sense of the error.

I agree this is a problem in scikits.ann, however it was working fine with numpy 1.5.1 and broke due to a change we made in 1.6.0. So it makes sense to limit the damage.

My preferred option is to emit a warning, and then convert to a list.

**Comment by thouis** [comment]
Comment in Trac by atmention:pearu, 2011-05-31

Ok, but let's implement this feature in numpy.distutils Extension class so
that the string swig_opts is converted to list as soon as possible.
(Actually, scikits.ann uses numpy.distutils way of declaring extension
and there we are free to introduce new features, w/o warnings)

There is one possible gotcha though. Say, if some of the swig options contains
space (eg in Windows paths often contain spaces) then the user needs to use
list version of swig_opts, otherwise simple split will cause problems.

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2011-06-02

Your gotcha tells me it's better to raise the warning anyway - a list is less fragile than a string with multiple arguments. This should do it:
https://github.com/rgommers/numpy/commit/f7e5924e31ff3b04e5b285e80c5b214f8439ba28

**Comment by thouis** [comment]
Comment in Trac by atmention:pearu, 2011-06-02

Yes, this looks good to me. 

Although, when reading the distutils code then the string swig_opts was "accepted" only because it was not actually used. Otherwise, the distutils code would have failed. My last years change "break" string swig_opts because it processed swig_opts earlier than distutils.

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2011-06-02

It's really not used? There'd even an example using it at http://docs.python.org/distutils/setupscript.html

I'll go ahead and commit this then.

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2011-06-02

Applied in commit:bf1e6f3
