### ISSUE TITLE
numpy 1.6.2 fails to compile with python 3.3.0 - ‘PyUnicodeObject’ has no member named ‘str’ (Trac #2221)

### ISSUE THREAD

**Issue by numpy-gitbot** [thouis/numpy-trac-migration#6010]
_Original ticket http://projects.scipy.org/numpy/ticket/2221 on 2012-10-03 by trac user tru, assigned to unknown._

numpy 1.6.2:
python3 setup.py build  --fcompiler=gnu95
(without site.cfg)

fails to build

git version as of 2012/10/03 (commit e18e7441700db0ff2fd8f51901aa416c63e35cbc)
compiles properly.

no issue with numpy 1.6.2 with python 3.2.3

**Comment by numpy-gitbot** [comment]
Attachment added by trac user tru on 2012-10-03: [error.log](http://projects.scipy.org/numpy/attachment/ticket/2221/error.log)

**Comment by numpy-gitbot** [comment]
_trac user tru wrote on 2012-10-03_

same issue as http://projects.scipy.org/numpy/ticket/1471 comment 13
see also
http://www.mail-archive.com/numpy-discussionatmention:scipy.org/msg38344.html

**Comment by numpy-gitbot** [comment]
_atmention:rgommers wrote on 2012-10-05_

This is fixed in master and 1.7.x. Numpy 1.6.2 was released well before Python 3.3, so it's not strange that those don't play well together. We're not planning on a 1.6.3 release, so closing as wontfix.
