### ISSUE TITLE
setuptools' develop mode broken (migrated from Trac #596)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#1203]
Original ticket http://projects.scipy.org/numpy/ticket/596
Reported 2007-10-21 by atmention:astraw, assigned to atmention:dmcooke.

As of svn 4271, I could not get the numpy.scons branch to install using the develop mode of setuptools:

Steps to reproduce:
1. {{{svn co http://svn.scipy.org/svn/numpy/branches/numpy.scons}}}
2. {{{python setup.py build}}} (may not be neccessary, but I did it)
3. Attempt to install using setuptools' develop mode (set {{{sys.argv[0], **name**, **main**}}} to their expected values in case setup.py introspect these)
   {{{python -c "import numpy.distutils, setuptools, sys;f='setup.py';sys.argv[0]=f;execfile(f,{'**file**':f,'**name**':'**main**'})" develop}}}
4. {{{python setupegg.py develop}}} also breaks, and there's a fairly load warning about numpy.distutils not being imported.

The error I get:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "setup.py", line 90, in <module>
        setup_package()
      File "setup.py", line 83, in setup_package
        configuration=configuration )
      File "/home/astraw/other-peoples-src/numpy.svn.scons/numpy/distutils/core.py", line 182, in setup
        return old_setup(**new_attr)
      File "distutils/core.py", line 151, in setup
      File "distutils/dist.py", line 974, in run_commands
      File "distutils/dist.py", line 994, in run_command
      File "/usr/lib/python2.5/site-packages/setuptools/command/develop.py", line 26, in run
        self.install_for_development()
      File "/usr/lib/python2.5/site-packages/setuptools/command/develop.py", line 81, in install_for_development
        self.process_distribution(None, self.dist, not self.no_deps)
      File "/usr/lib/python2.5/site-packages/setuptools/command/easy_install.py", line 497, in process_distribution
        self.install_egg_scripts(dist)
      File "/usr/lib/python2.5/site-packages/setuptools/command/develop.py", line 111, in install_egg_scripts
        script_path = os.path.abspath(convert_path(script_name))
      File "/usr/lib/python2.5/posixpath.py", line 402, in abspath
        if not isabs(path):
      File "/usr/lib/python2.5/posixpath.py", line 49, in isabs
        return s.startswith('/')
    AttributeError: 'function' object has no attribute 'startswith'

Thanks so far for your work on the scons branch -- I hope I can get it to work soon!

**Comment by thouis** [comment]
Comment in Trac by atmention:astraw, 2007-10-24

Hmm, I've just noticed/remembered that develop mode didn't work in 1.0.3, either. And I also notice that installing the numpy.scons branch (r4274) with setuptools seems to work fine. So, I would close this bug, if I had permission, as "wontfix".

**Comment by thouis** [comment]
Comment in Trac by atmention:dmcooke, 2007-10-24

Develop mode would be nice, but you're right, it doesn't work in non-scons anyways :)

**Comment by thouis** [comment]
Comment in Trac by atmention:rkern, 2007-12-13

The trunk now works with 'develop' mostly correctly. The remaining issue of making numpy itself truly 'develop'able is where it puts the generated header files. numpy will run as 'develop'ed, but you can't build scipy from it.

**Comment by thouis** [comment]
Comment in Trac by atmention:rkern, 2007-12-13

Also, you need to import setuptools before numpy.distutils.

**Comment by thouis** [comment]
Comment in Trac by atmention:astraw, 2007-12-13

Indeed, I have been working with numpy SVN trunk all afternoon installed via the above script and have not had any troubles. Apart from the header file issue, things seem fixed.

**Comment by thouis** [comment]
Comment in Trac by atmention:cournape, 2007-12-14

Did you try with scons too ?

**Comment by thouis** [comment]
Comment in Trac by atmention:charris, 2008-02-24

On the numpy-discussion list David wrote:

''
I would change the ticket title to setuptools develop mode doesn't work,
and then mark it as fixed. I don't think that develop mode works with
numscons, though, but that should be a separate issue.
''

I can't change the summary, but I am going to close this ticket anyway.

**Comment by thouis** [comment]
Comment in Trac by atmention:cournape, 2008-02-25
